service: myservice
provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-2:*:*"
functions:
  trigger-report:
    handler: controllers/adn.trigger
  mutant:
    handler: controllers/adn.mutant
    events:
      -
        http:
          path: mutant
          method: post
          cors: true
          integration: LAMBDA
  stats:
    handler: controllers/adn.stats
    events:
      -
        http:
          path: stats
          method: get
          cors: true
          integration: LAMBDA
resources:
  Resources:
    TableNotification:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: adn
            AttributeType: S
          - 
            AttributeName: mutan
            AttributeType: N
        KeySchema:
          -
            AttributeName: adn
            KeyType: HASH
          -
            AttributeName: mutan
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: XMEN
    TableReports:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: identity
            AttributeType: S
        KeySchema:
          -
            AttributeName: identity
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: REPORTS